name: Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "22"

      - run: npm install --omit=dev

      - run: npx @vscode/vsce package --skip-license

      - uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: "*.vsix"

  Release:
    needs: Build
    uses: gesslar/Maint/.github/workflows/ReleaseOnly.yaml@main
    secrets: inherit
    with:
      quality_check: "Quality"
      artefacts: '["vsix"]'
    permissions:
      contents: write
